project:
  title: projet oracle
  output-dir: output
title: "Rapport projet Oracle"
self-contained: true
output-file: rapport_JOURDAM_VOROS
title-block-style: default
title-block-banner: true
author-title: Auteurs
author: 
  - name: Joshua JOURDAM
  - name: Matthias VOROS
date: today
lang: fr
format:
  html :
    embed-resources: true
toc: true
toc-depth: 3
number-sections: true
filters:
   - include-code-files
abstract: |
  ```uml
  Region (idregion, nom)
  Vin (idvin, nom, appellation, type, provenance*)
  Article (idarticle, millesime, contenance, prixht, vin*)
  Client (idclient, nom, age, habite*);
  Achat (idachat, article*, client*, dateachat, quantite, ristourne)
  ```
language:
  section-title-abstract: "Schéma logique"
