CREATE OR REPLACE TRIGGER EMPECHER_ACHAT_ARTICLE BEFORE
    INSERT ON ACHAT FOR EACH ROW
DECLARE
    DATE_ACHAT_PRECEDENT DATE;
BEGIN
    SELECT
        MAX(DATEACHAT) INTO DATE_ACHAT_PRECEDENT
    FROM
        ACHAT
    WHERE
        ARTICLE = :NEW.ARTICLE
        AND DATEACHAT < :NEW.DATEACHAT;
    IF (DATE_ACHAT_PRECEDENT IS NOT NULL
    AND :NEW.DATEACHAT - DATE_ACHAT_PRECEDENT <= 3) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Achat non autorisé : cet article a été acheté il y a moins de 3 jours');
    END IF;
END;
 -- Tests
 INSERT INTO ACHAT VALUES (
    22341,
    23,
    3,
    TO_DATE('13/03/2023', 'DD/MM/YYYY'),
    10,
    7
);
INSERT INTO ACHAT VALUES (
    22341,
    23,
    3,
    TO_DATE('14/03/2023', 'DD/MM/YYYY'),
    10,
    7
);
INSERT INTO ACHAT VALUES (
    22341,
    23,
    3,
    TO_DATE('15/03/2023', 'DD/MM/YYYY'),
    10,
    7
);
INSERT INTO ACHAT VALUES (
    22347,
    23,
    3,
    TO_DATE('15/03/2023', 'DD/MM/YYYY'),
    10,
    7
);
SELECT
    MAX(DATEACHAT)
FROM
    ACHAT
WHERE
    ARTICLE = 23;