-- Soit la table d'audit ci-dessous qui permet de suivre les achats de vins.   

-- CREATE TABLE AUDIT_ACHAT_VIN  
--     (NOM_CLIENT VARCHAR2 (30) NOT NULL,  
--     NOM_VIN VARCHAR2 (30) NOT NULL,  
--     NOM_REGION_VIN VARCHAR2(20) NOT NULL,    
--     APPELATION VARCHAR2 (30) NOT NULL,  
--     QUANTITE_COMMANDEE INTEGER,  
--     DATE_ACHAT DATE NOT NULL);

CREATE TABLE AUDIT_ACHAT_VIN (
    NOM_CLIENT VARCHAR2 (30) NOT NULL,
    NOM_VIN VARCHAR2 (30) NOT NULL,
    NOM_REGION_VIN VARCHAR2(20) NOT NULL,
    APPELATION VARCHAR2 (30) NOT NULL,
    QUANTITE_COMMANDEE INTEGER,
    DATE_ACHAT DATE NOT NULL
);

-- Écrire un trigger qui agit après une insertion dans la table ACHAT en remplissant la table AUDIT_ACHAT_VIN.

CREATE OR REPLACE TRIGGER TRIGGER_AUDIT_VIN AFTER
    INSERT ON ACHAT FOR EACH ROW
DECLARE
    NOM_CLIENT     VARCHAR(20);
    NOM_VIN        VARCHAR(20);
    NOM_REGION_VIN VARCHAR(20);
    APPELATION     VARCHAR(20);
BEGIN
    SELECT
        CLIENT.NOM,
        VIN.NOM,
        REGION.NOM,
        VIN.APPELLATION INTO NOM_CLIENT,
        NOM_VIN,
        NOM_REGION_VIN,
        APPELATION
    FROM
        CLIENT,
        VIN,
        REGION,
        ARTICLE
    WHERE
        :NEW.CLIENT = CLIENT.IDCLIENT
        AND :NEW.ARTICLE = IDARTICLE
        AND ARTICLE.VIN = VIN.IDVIN
        AND VIN.PROVENANCE=REGION.IDREGION;
    INSERT INTO AUDIT_ACHAT_VIN VALUES (
        NOM_CLIENT,
        NOM_VIN,
        NOM_REGION_VIN,
        APPELATION,
        :NEW.QUANTITE,
        :NEW.DATEACHAT
    );
END;

-- Test

INSERT INTO ACHAT VALUES (
    500,
    94,
    19,
    TO_DATE('25/11/2021', 'DD/MM/YYYY'),
    3,
    7
); -- Pass

SELECT
    *
FROM
    AUDIT_ACHAT_VIN; -- Pass