CREATE TABLE AUDIT_ACHAT_VIN (
    NOM_CLIENT VARCHAR2 (30) NOT NULL,
    NOM_VIN VARCHAR2 (30) NOT NULL,
    NOM_REGION_VIN VARCHAR2(20) NOT NULL,
    APPELATION VARCHAR2 (30) NOT NULL,
    QUANTITE_COMMANDEE INTEGER,
    DATE_ACHAT DATE NOT NULL
);