-- Créer une vue qui pour chaque article affiche la quantité totale achetée à ce jour (tout client confondu).

CREATE OR REPLACE VIEW QUANTITE_TOTALE_ACHETEE AS
    SELECT
        ARTICLE.IDARTICLE,
        ARTICLE.MILLESIME,
        ARTICLE.CONTENANCE,
        SUM(ACHAT.QUANTITE*ARTICLE.CONTENANCE) AS QUANTITE_TOTALE_ACHETEE
    FROM
        ARTICLE,
        ACHAT
    WHERE
        ARTICLE.IDARTICLE = ACHAT.ARTICLE
    GROUP BY
        ARTICLE.IDARTICLE,
        ARTICLE.MILLESIME,
        ARTICLE.CONTENANCE;

SELECT * FROM QUANTITE_TOTALE_ACHETEE;
